org.gradle.jvmargs=-Xmx1536m -Xss1m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
kotlin.daemon.jvm.options=-Xmx768m
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
MESHGRAM_DONATION_URL=https://yookassa.ru/my/i/apXuo0ctyNYY/l
MESHGRAM_UPDATE_MANIFEST_URL=https://raw.githubusercontent.com/Who2215/MeshGram/main/site/release.json
MESHGRAM_RELEASE_PUBLIC_KEY_BASE64=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAhfjX38UCY+2jxK2x3synosfZl3+HVHaSS2eEZT4X15WNLa0+Woap7vnndV5DF0pDmtzVAAmfQO/TZl0HDeTqw==
