org.gradle.jvmargs=-Xmx1536m -Xss1m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
kotlin.daemon.jvm.options=-Xmx768m
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
MESHGRAM_DONATION_URL=https://yookassa.ru/my/i/apXuo0ctyNYY/l
