$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$assets = Join-Path $root 'app/src/main/assets/stickers/noto'
$drawables = Join-Path $root 'app/src/main/res/drawable-nodpi'
$licenses = Join-Path $root 'app/src/main/assets/licenses'
New-Item -ItemType Directory -Force $assets,$drawables,$licenses | Out-Null
$api = Invoke-RestMethod 'https://googlefonts.github.io/noto-emoji-animation/data/api.json'
$records = [System.Collections.Generic.List[object]]::new()
$groups = @(@{category='faces'; names=@('Smileys and emotions'); count=50; priority='1f602 1f923 1f62d 1f92f 1f621 1f92c 1f608 1f47f 1f480 1f4a9 1f921 1f47b 1f47d 1f916 1f639 1f63b 1f63c 1f640 1f63f 1f63e 1f92a 1f644 1f60f 1f928 1f9d0 1f92d 1fae0 1f631 1f92e 1f922 1f976 1f975 1f974 1f634 1f924 1f973 1f929 1f60e 1f97a 1f979 1f605 1f618 1f970 1f914 1f92b 1f910 1f611 1f636 1f60d 1f607'},
    @{category='animals'; names=@('Animals and nature'); count=20; priority='1f438 1f412 1f99d 1f9a5 1f419 1f980 1f427 1fabf 1f423 1f987 1f409 1f996 1f422 1f40d 1f407 1f429 1f416 1f9a6 1f994 1f41d 1f415'},
    @{category='fun'; names=@('Food and drink','Activities and events','Objects'); count=10; priority='1f37f 2615 1f355 1f382 1f3b2 1f4b8 1f4a3 1faab 1f3ad 1faa9'})
foreach($group in $groups) {
    $count=0
    $priority = $group.priority.Split(' ')
    $selected = @($priority | ForEach-Object { $code=$_; $api.icons | Where-Object {$_.codepoint -eq $code} })
    $selected += @($api.icons | Where-Object {$_.categories[0] -in $group.names -and $_.codepoint -match '^[0-9a-f]+$' -and $_.codepoint -notin $priority})
    foreach($icon in $selected) {
        if($count -eq $group.count){break}
        $code=$icon.codepoint
        $id='noto'+(-join ($code.ToCharArray() | ForEach-Object {[char](97+[Convert]::ToInt32([string]$_,16))}))
        $url="https://fonts.gstatic.com/s/e/notoemoji/latest/$code/lottie.json"
        $preview="https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/128/emoji_u$code.png"
        try {
            $json=if(Test-Path "$assets/$id.json"){Get-Content "$assets/$id.json" -Raw}else{(Invoke-WebRequest $url).Content}
            $animation=$json | ConvertFrom-Json
            if($animation.op -le $animation.ip -or $animation.fr -le 0 -or $json -notmatch '"a"\s*:\s*1') {continue}
            if(@($animation.assets | Where-Object {$_.p -and $_.p -notlike 'data:*'}).Count){continue}
            if(!(Test-Path "$drawables/$id.png")){Invoke-WebRequest $preview -OutFile "$drawables/$id.png"}
            [IO.File]::WriteAllText("$assets/$id.json",$json,[Text.UTF8Encoding]::new($false))
            $records.Add([ordered]@{id=$id;codepoint=$code;category=$group.category;label=$icon.tags[0].Trim(':');
                source=$url;previewSource=$preview;author='Google Fonts';license='CC-BY-4.0';previewLicense='Apache-2.0';
                sha256=(Get-FileHash "$assets/$id.json").Hash.ToLower();previewSha256=(Get-FileHash "$drawables/$id.png").Hash.ToLower()})
            $count++
        } catch {Write-Host "Skipped $code : $($_.Exception.Message)"}
    }
    if($count -ne $group.count){throw "Insufficient animations: $($group.category) $count"}
}
$records | ConvertTo-Json -Depth 5 | Set-Content "$assets/sources.json" -Encoding utf8
Invoke-WebRequest 'https://creativecommons.org/licenses/by/4.0/legalcode.txt' -OutFile "$licenses/noto-animation-CC-BY-4.0.txt"
Invoke-WebRequest 'https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/LICENSE' -OutFile "$licenses/noto-preview-Apache-2.0.txt"
Invoke-WebRequest 'https://www.apache.org/licenses/LICENSE-2.0.txt' -OutFile "$licenses/Apache-2.0.txt"
@'
Animated Noto Emoji by Google Fonts, CC BY 4.0.
https://googlefonts.github.io/noto-emoji-animation/
https://creativecommons.org/licenses/by/4.0/
Animations are unmodified. Static PNG previews by Google, Apache 2.0.
See stickers/noto/sources.json for source URLs and checksums.
'@ | Set-Content "$licenses/noto-NOTICE.txt"
$lines=@('package com.meshchat.app.ui','','import com.meshchat.app.R','','// Generated by tools/import_noto_stickers.ps1; IDs are permanent.','object NotoStickerCatalog {','    val entries = listOf(')
foreach($r in $records){$lines += "        StickerDefinition(`"$($r.id)`", `"noto`", StickerKind.LOTTIE, `"$($r.category)`", `"stickers/noto/$($r.id).json`", R.drawable.$($r.id), `"Google Fonts / CC BY 4.0`"),"}
$lines += @('    )','}')
$lines | Set-Content (Join-Path $root 'app/src/main/java/com/meshchat/app/ui/NotoStickerCatalog.kt')
$size=(Get-ChildItem $assets,$drawables -File | Measure-Object Length -Sum).Sum
if($size -gt 16MB){throw "Sticker resources exceed 16 MiB: $size"}
Write-Host "Imported $($records.Count) animations; resource bytes $size"
